In [1]:
from utils import Agent, Road, Trpf, read_config
from itertools import repeat
import numpy as np

# Functions

In [2]:
def get_route_choices(agents, route_count):
    choices = list(map(lambda agent: agent.choose_route(), agents))
    route_traveller_counts = np.bincount(choices, minlength = route_count)[:, np.newaxis]
    return choices, route_traveller_counts

def get_route_costs(roads, choices, route_traveller_counts):
    road_traveller_counts = np.array(route_to_road * route_traveller_counts)
    list(map(lambda count, road: road.add_travellers(count), road_traveller_counts[:,0], roads))
    road_costs = np.array(list(map(lambda road: road.report_cost(), roads)))[:, np.newaxis]
    route_costs = np.array(road_to_route * road_costs)
    return route_costs

def give_costs(agents, choices, route_costs):    
    list(map(lambda agent, choice: agent.recieve_travel_cost(route_costs[choice,0]), agents, choices))
    
def get_reports(agents, trpf, choices, excess_traveller_counts):
    reports = list(map(lambda agent, choice, excess: agent.report_congestion(excess[choice,0]),\
        agents, choices, repeat(excess_traveller_counts)))
    list(map(lambda route, report: trpf.recieve_report(route, report), choices, reports))
    
def give_trpfs(trpf, trpf_agents):
    route_trpfs = trpf.calculate_trpf()
    list(map(lambda agent, trpf: agent.recieve_trpf(trpf), trpf_agents, repeat(route_trpfs)))

# Read the configuration

In [3]:
simulation_folder = '/home/ihsan/Research/TrafficFlow/simulations/5/'
traffic_file = simulation_folder + 'traffic.properties'
roadnet_file = simulation_folder + 'roadnet.csv'

config = read_config(traffic_file, roadnet_file)

tresholds = config['tresholds']
weights = config['weights']
trpf_use_percent = config['trpf_use_percent']
t = config['t']
agent_count = config['agent_count']
change_percent = config['change_percent']
routes = config['routes']
route_opts = np.array(config['route_opts'])[:, np.newaxis]
round_count = config['round_count']
road_params = config['road_params']

# Initialize the simulation

In [4]:
route_count = len(routes)

trpf = Trpf(route_count, round_count, t)

roads = []
road_inds = {}
for i, params in enumerate(road_params.itertuples(index=False)):
    road = Road(*params)
    roads.append(road)
    road_name = params[0] + params[1] # Node 1 + Node 2
    road_inds[road_name] = i
    
agents = []
trpf_agents = []
for tag in range(agent_count):
    agent = Agent(tag, tresholds, weights, route_count, change_percent, trpf_use_percent)
    agents.append(agent)
    if agent.uses_trpf():
        trpf_agents.append(agent)
trpf_agents = trpf_agents

route_to_road = np.zeros((len(roads), len(routes)))
for i, route in enumerate(routes):
    for e in range(1, len(route)):
        road_name = route[e-1] + route[e]
        j = road_inds[road_name]
        route_to_road[j, i] = 1
route_to_road = np.matrix(route_to_road)
road_to_route = route_to_road.T 

historic_choices = np.zeros((round_count, route_count))
print('Number of trpf users: {}, Number of routes: {}, Number of roads:{}'.format(len(trpf_agents),\
    route_count, len(roads)))

Number of trpf users: 187, Number of routes: 3, Number of roads:7


# Simulation

In [5]:
while trpf.start_new_round():
    choices, route_traveller_counts = get_route_choices(agents, route_count)
    excess_traveller_counts = np.absolute(route_traveller_counts - route_opts)
    route_costs = get_route_costs(roads, choices, route_traveller_counts)
    give_costs(agents, choices, route_costs)
    get_reports(agents, trpf, choices, excess_traveller_counts)
    give_trpfs(trpf, trpf_agents)
    # Save the choices
    historic_choices[trpf.current_round,:] = route_traveller_counts[:,0]

# Results

In [6]:
means = np.mean(historic_choices[-100:], axis=0)
stds = np.std(historic_choices[-100:], axis=0)
print('Means: ', means)
print('Standard deviations:', stds, '\n')
print(historic_choices)

Means:  [  18.37   62.69  118.94]
Standard deviations: [  5.15297002  16.45156224  17.27704836] 

[[  71.   56.   73.]
 [  69.   60.   71.]
 [  57.   49.   94.]
 [  48.   43.  109.]
 [  38.   32.  130.]
 [  26.   41.  133.]
 [  23.   71.  106.]
 [  22.   94.   84.]
 [  20.   73.  107.]
 [  20.   60.  120.]
 [  17.   52.  131.]
 [  16.   42.  142.]
 [  23.   50.  127.]
 [  21.   74.  105.]
 [  29.   71.  100.]
 [  22.   59.  119.]
 [  20.   40.  140.]
 [  17.   37.  146.]
 [  12.   74.  114.]
 [   9.  103.   88.]
 [   8.   82.  110.]
 [   6.   72.  122.]
 [   5.   53.  142.]
 [   5.   45.  150.]
 [  21.   44.  135.]
 [  16.   82.  102.]
 [  15.  101.   84.]
 [  12.   82.  106.]
 [  11.   68.  121.]
 [  11.   57.  132.]
 [  10.   46.  144.]
 [  20.   50.  130.]
 [  17.   79.  104.]
 [  27.   71.  102.]
 [  24.   57.  119.]
 [  21.   48.  131.]
 [  18.   36.  146.]
 [  17.   64.  119.]
 [  16.   89.   95.]
 [  13.   74.  113.]
 [  12.   60.  128.]
 [  12.   48.  140.]
 [  26.   58.  116.]